# jupyter-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-notebook
  namespace: jupyter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter-notebook
  template:
    metadata:
      labels:
        app: jupyter-notebook
    spec:
      containers:
        - name: jupyter
          image: m6f13/my-jupyter:latest
          ports:
            - containerPort: 8888
          envFrom:
            - configMapRef:
                name: spark-config
          env:
            - name: JAVA_HOME
              value: "/usr/lib/jvm/java-11-openjdk-amd64"